import styled from "@emotion/styled";
import { Card, Divider } from "@mui/material";
import InfoImgCard from "../components/ShowCards/InfoImgCard";
import InfoCard from "../components/ShowCards/InfoCard";
import TitleCard from "../components/ShowCards/TitleCard";

export default function TermsAndConditions() {
  return (
    <Root>
      <TitleCard text="TERMS OF SERVICE " />
      {/* <div className="content"> */}

      {content.map((section, index) => (
        <TranslucentCard key={index} elevation={9}>
          <InfoCard title={section.title} description={section.description} />
        </TranslucentCard>
      ))}
      {/* </div> */}
    </Root>
  );
}

// Divider;
const Root = styled.div`
  display: grid;

  gap: 2rem;
  justify-content: start;
  justify-items: start;
  padding: 2rem;
  @media (max-width: 50px) {
    padding: 1rem;
  }
  margin-top: 1rem;

`;

const TranslucentCard = styled(Card)`
  max-width: 60rem;
  border-radius: 1.2rem;
  box-shadow: none;
  backdrop-filter: blur(8px);
  background: rgb(11, 22, 53, 0.7);
  color: rgb(160, 170, 180);
  z-index: 10;
  display: grid;
  align-items: stretch;
  gap: 2rem;
  padding: 2rem;
  @media (max-width: 600px) {
    padding: 1rem;
  }
`;

const content = [
  {
    title: "",
    description: (
      <>
        PLEASE NOTE THAT THE SERVICES (AS DEFINED BELOW) ARE PRIMARILY FOR
        PEOPLE WHO NEED A KNOWLEDGE, EDUCATIONAL COURSE OF TECHNICAL AND
        FUNDAMENTAL ANALYSIS FOUNDATIONS EXAMINATIONS IN RELATION TO STOCK
        MARKET, AND TO ENCOURAGE AND UPGRADE THEIR SKILL, KNOWLEDGE AND
        INTEREST. PLEASE ALSO NOTE THAT THE INFORMATION PROVIDED IN THE SERVICES
        (AS DEFINED BELOW) IS FOR INFORMATIONAL PURPOSES ONLY AND NOT INTENDED
        TO BE A SUBSTITUTE FOR PROFESSIONAL, INVESTMENT ADVICE, ALWAYS CONSULT
        WITH EXPERT, OR COUNSELLORS BEFORE USING OR PERFORMING ANY PRODUCT,
        SERVICE, PROCEDURE, METHOD OR INFORMATION DISCUSSED IN THE SERVICES.
        <br />
        <br />
        THIS EDUCATIONAL COURSE OF TECHNICAL AND FUNDAMENTAL ANALYSIS ARE BASED
        ON AYMPER MARKETS AUTHOR’S OR OWNER’S PERSONAL OBSERVATIONS AND
        PERSPECTIVE. WE ARE COMMITTED TO PROVIDE COURSE AS HIGHEST QUALITY AS
        POSSIBLE AND MAKING E-LEARNING POSSIBILITY ON OUR WEBSITE PORTAL. ANY
        PERSON WHO IS ACCESSING OR HAS ACCESSED ANY INFORMATION OR DATA FROM THE
        OUR WEBSITE ACKNOWLEDGES THAT IT MAY HAVE SPELLING ERROR OR HAVE LESS
        ACCURACY OF PARTICULAR INFORMATION OR INCOMPLETE INFORMATION. THE
        WRITTEN CONTENT AND GRAPHICAL CONTENT ON THIS WEBSITE COULD INCLUDE
        TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY
        ADDED TO THE INFORMATION HEREIN. AYMPER MARKETS MAY MAKE IMPROVEMENTS OR
        MODIFY FULL COURSE AT ANY TIME. AYMPER MARKETS MAKES NO REPRESENTATIONS
        ABOUT THE ACCURACY OF THE INFORMATION CONTAINED IN THE WEB CONTENT AND
        GRAPHICAL CONTENT ON THIS WEB SITE FOR ANY PURPOSE.
        <br />
        <br />
        WE DO NOT PROVIDE ANY INVESTMENT ADVICE OR SELL TIPS. AYMPER MARKETS IS
        ONLY FOR USE AS EDUCATIONAL PURPOSE. AYMPER MARKETS IS NOT RESPONSIBLE
        FOR ANY KIND OF PROFIT OR LOSS OCCURS FROM THE STOCK MARKET. USER WILL
        BE RESPONSIBLE FOR ALL PROFIT AND LOSS AS ALL THE INVESTMENT DECISION OF
        TAKING TRADES AND OPENING ORDERS BE SOLE DECISION OF USER AFTER
        COMPLETING THE COURSE.
      </>
    ),
  },
  {
    title: "TERMS AND CONDITION",
    description: (
      <>
        1). BEFORE YOU REGISTER YOUR ACCOUNT, TO CREATE AN ACCOUNT, TO BE
        ELIGIBLE OR TO OTHERWISE USE THIS WEBSITE, YOU MUST BE AT LEAST EIGHTEEN
        (18) YEARS OLD OR THE AGE OF MAJORITY IN YOUR STATE OR PROVINCE OF
        RESIDENCE OR INDIAN GOVERNMENT ALLOWS AGE, WHICHEVER IS GREATER
        <br />
        <br />
        2). WE MAY MODIFY OUR TERMS AND CONDITION AT ANY TIME. MODIFICATIONS
        WILL BE POSTED IMMEDIATELY, AND YOUR USE OF THE SITE AFTER SUCH CHANGES
        HAVE BEEN POSTED WILL CONSTITUTE YOUR AGREEMENT TO THE MODIFIED TERMS OF
        USE AND ALL OF THE CHANGES. YOU SHOULD READ THESE TERMS OF USE EACH TIME
        YOU ACCESS, AND PRIOR TO USING, THE SITE.
        <br />
        <br />
        3). CONTENT ON THE SITE MAY BE DISPLAYED SOLELY FOR YOUR PERSONAL,
        NON-COMMERCIAL USE. YOU MAY NOT REPRODUCE COPY, SELL, RESELL OR
        OTHERWISE EXPLOIT THIS SITE, OR ANY PORTION OF THIS SITE. NO PART OF ANY
        CONTENT, FORM OR DOCUMENT MAY BE REPRODUCED IN ANY FORM OR INCORPORATED
        INTO ANY INFORMATION RETRIEVAL SYSTEM, ELECTRONICALLY OR MECHANICALLY.
        WE RESERVE THE RIGHT TO REFUSE SERVICE AND TERMINATE ACCOUNTS IN OUR
        SOLE DISCRETION. WHEN YOU SIGN UP TO BECOME A MEMBER, YOU WILL ALSO BE
        ASKED TO CHOOSE A PASSWORD. YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING
        THE CONFIDENTIALITY OF YOUR PASSWORD. YOU AGREE NOT TO USE THE ACCOUNT,
        USERNAME, PASSWORD OR ANY OTHER PERSONAL DETAILS OF ANOTHER MEMBER AT
        ANY TIME OR TO DISCLOSE YOUR PASSWORD TO ANY THIRD PARTY. YOU AGREE TO
        NOTIFY US IMMEDIATELY IF YOU SUSPECT ANY UNAUTHORIZED USE OF YOUR
        ACCOUNT OR ACCESS TO YOUR PASSWORD WITHIN 24 HOURS. YOU ARE SOLELY
        RESPONSIBLE FOR ANY AND ALL USE OF YOUR ACCOUNT.
        <br />
        <br />
        4) YOU AGREE TO USE THE SITE IN A MANNER CONSISTENT WITH APPLICABLE LAWS
        AND REGULATIONS. YOU AGREE NOT TO USE A FALSE E-MAIL ADDRESS,
        IMPERSONATE ANY PERSON OR ENTITY OR OTHERWISE MISLEAD AS TO YOUR
        PROFESSIONAL PROFILE FOR THE PURPOSE OF GAINING ACCESS TO OPPORTUNITIES.
        AT OUR SOLE DISCRETION, WE MAY REQUIRE PROOF THAT YOU MEET THESE
        CONDITIONS AND HAVE CONNECTION WITH ACCOUNT, YOU ARE REQUIRED TO SUBMIT
        YOUR AGE, GENDER, FIRST NAME, LAST NAME, A VALID EMAIL ADDRESS AND YOUR
        PHONE NUMBER TO GET CERTIFICATION, IF YOU VIOLATE THESE TERMS WE MAY,
        WITH OR WITHOUT PRIOR WARNING, TERMINATE YOUR ACCOUNT WITHOUT
        COMPENSATION. THIS AGREEMENT IS PERSONAL TO YOU, AND YOU MAY NOT ASSIGN
        YOUR RIGHTS OR OBLIGATIONS TO ANYONE. YOU ARE ALLOWED TO CREATE ONE
        ACCOUNT WITH US. PLEASE FOLLOW OUR ONE ACCOUNT POLICY AS CREATING MORE
        THAN ONE ACCOUNT IS A VIOLATION OF OUR TERMS AND CONDITION.
        <br />
        <br />
        5). THE CONTENT DISPLAYED ON THE WEBSITE (WWW.AYMPER.COM), INCLUDING
        TEXT, GRAPHICS, LOGOS, ARTWORK, AUDIO CLIPS, TRADEMARKS, IS THE
        EXCLUSIVE PROPERTY OF AYMPER MARKETS. AND IS PROTECTED BY COPYRIGHT AND
        REGISTERED.
        <br />
        <br />
        6). THIS EDUCATIONAL COURSE OF TECHNICAL AND FUNDAMENTAL ANALYSIS ARE
        BASED ON AYMPER MARKETS AUTHOR’S PERSONAL OBSERVATIONS AND PERSPECTIVE.
        WE ARE COMMITTED TO PROVIDE COURSE AS HIGHEST QUALITY AS POSSIBLE AND
        MAKING E-LEARNING POSSIBILITY ON OUR WEBSITE PORTAL. ANY PERSON WHO IS
        ACCESSING OR HAS ACCESSED ANY INFORMATION OR DATA FROM THE OUR WEBSITE
        ACKNOWLEDGES THAT IT MAY HAVE SPELLING ERROR OR HAVE LESS ACCURACY OF
        PARTICULAR INFORMATION OR INCOMPLETE INFORMATION. THE WRITTEN CONTENT
        AND GRAPHICAL CONTENT ON THIS WEBSITE COULD INCLUDE TECHNICAL
        INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO
        THE INFORMATION HEREIN. AYMPER MARKETS MAY MAKE IMPROVEMENTS OR MODIFY
        FULL COURSE AT ANY TIME. AYMPER MARKETS MAKES NO REPRESENTATIONS ABOUT
        THE ACCURACY OF THE INFORMATION CONTAINED IN THE WEB CONTENT AND
        GRAPHICAL CONTENT ON THIS WEB SITE FOR ANY PURPOSE.
        <br />
        <br />
        7). TRADING AND INVESTMENT ARE SUBJECT TO MARKET RISK. ALL THE
        STRATEGIES AND METHODOLOGY IN THE COURSE WE DELIVER ARE FOR EDUCATION
        PURPOSE ONLY. THE COURSE IN THIS WEBSITE EITHER WHATEVER COURSE WE
        PROVIDE ARE FOR EDUCATION PURPOSE. WE DON’T PROVIDE ANY INVESTMENT
        ADVICE OR SELL TIPS. AYMPER MARKETS IS NOT RESPONSIBLE FOR ANY KIND OF
        PROFIT OR LOSS OCCURS FROM THE STOCK MARKET.
        <br />
        <br />
        8). BY SIGNING UP ON OUR WEBSITE, YOU ACKNOWLEDGE THAT ALL INFORMATION
        CONTAINED ON THE SITE MAY BE PROTECTED, IN ALL FORMS AND MEDIA, BY ONE
        OR MORE VALID COPYRIGHTS, PATENTS, TRADEMARKS, TRADE SECRETS, OR OTHER
        PROPRIETARY RIGHTS, AND THAT ALL SUCH RIGHTS ARE OWNED BY AYMPER
        MARKETS.,
        <br />
        <br />
      </>
    ),
  },
  {
    title: "ACCEPTANCE OF TERMS",
    description: `“AYMPER MARKETS” PROVIDES ITS INTERNET SITES AND THE CONTENT, PRODUCTS AND SERVICES OFFERED ON OR THROUGH THOSE SITES, TO YOU SUBJECT TO THE FOLLOWING TERMS OF SERVICE (“TOS”). YOUR USE OF THE SERVICES IN WHOLE OR IN PART CONSTITUTES YOUR BINDING ACCEPTANCE OF THESE TOS. IF YOU DO NOT AGREE TO THESE TOS, YOU SHOULD NOT USE THE SERVICES. SOME SERVICES MAY BE SUBJECT TO ADDITIONAL POSTED RULES, POLICIES AND TERMS. WHEN YOU USE THOSE SERVICES, YOU AND “AYMPER MARKETS” SHALL BE SUBJECT TO THOSE ADDITIONAL CONDITIONS, WHICH ARE INCORPORATED BY REFERENCE INTO THESE TOS (AND, CONSEQUENTLY, FORM PART OF YOUR AGREEMENT WITH US). OTHER SERVICES MAY BE GOVERNED BY DIFFERENT USAGE TERMS. IN THE EVENT OF AN INCONSISTENCY BETWEEN THESE TOS AND ANY ADDITIONAL POSTED CONDITIONS OR SEPARATE USAGE TERMS, THE PROVISIONS OF THE ADDITIONAL CONDITIONS AND/OR SEPARATE USAGE TERMS SHALL CONTROL. BECAUSE WE MAY MODIFY ALL OR ANY PART OF THESE TOS FROM TIME TO TIME WITHOUT NOTICE TO YOU, YOU SHOULD CHECK BACK OFTEN SO YOU ARE AWARE OF YOUR CURRENT RIGHTS AND RESPONSIBILITIES. YOUR CONTINUED USE OF A GIVEN SERVICE AFTER CHANGES TO THE TOS HAVE BEEN PUBLISHED ON THAT SERVICE CONSTITUTES YOUR BINDING ACCEPTANCE OF THE UPDATED TOS. IF AT ANYTIME THE TOS ARE NO LONGER ACCEPTABLE TO YOU, YOU SHOULD IMMEDIATELY CEASE ALL USE OF THE SERVICES.`,
  },
  {
    title: "GENERAL RULES OF CONDUCT",
    description: (
      <>
        YOUR USE OF THE SERVICES IS SUBJECT TO ALL APPLICABLE LOCAL, STATE,
        NATIONAL AND INTERNATIONAL LAWS AND REGULATIONS, AND YOU AGREE NOT TO
        VIOLATE SUCH LAWS AND REGULATIONS. IN ADDITION, YOU AGREE THAT:
        <br />
        <br />
        YOU WILL NOT INTERFERE WITH ANOTHER MEMBER’S USE AND ENJOYMENT OF THE
        SERVICES; YOU WILL NOT INTERFERE WITH OR DISRUPT THE SECURITY MEASURES
        OF THE SERVICES; YOU WILL NOT INTERFERE WITH OR DISRUPT NETWORKS
        CONNECTED TO THE SERVICES, AND WILL COMPLY WITH ALL REGULATIONS,
        POLICIES AND PROCEDURES OF SUCH NETWORKS; AND YOU WILL COMPLY WITH INDIA
        LAW REGARDING THE TRANSMISSION OF TECHNICAL DATA EXPORTED FROM THE
        INDIA.
        <br />
        <br />
        YOU WILL NOT USE THE SERVICES TO SEND OR RESULT IN THE TRANSMISSION OF
        JUNK E-MAIL, CHAIN LETTERS, DUPLICATIVE OR UNSOLICITED MESSAGES, OR
        SO-CALLED “SPAMMING”; HARM MINORS IN ANYWAY; PROMOTE OR GENERATE REVENUE
        FOR ANY BUSINESS OR COMMERCIAL PURPOSES, WHETHER OR NOT FOR A CHARGE OR
        THROUGH LINKING WITH ANY OTHER WEB SERVICES OR PAGES, UNLESS AUTHORIZED
        BY “AYMPER MARKETS”; IMPERSONATE ANY PERSON OR ENTITY; INTENTIONALLY OR
        UNINTENTIONALLY VIOLATE ANY APPLICABLE LOCAL, STATE, NATIONAL OR
        INTERNATIONAL LAW; “STALK” OR OTHERWISE HARASS ANOTHER;
        <br />
        <br />
        YOU WILL NOT COLLECT OR STORE PERSONAL DATA ABOUT OTHER USERS; AND YOU
        WILL NOT REPRODUCE, MODIFY, DISTRIBUTE OR REPUBLISH MATERIALS CONTAINED
        ON THE SERVICE (EITHER DIRECTLY OR BY LINKING) WITHOUT OUR PRIOR WRITTEN
        PERMISSION. YOU WILL NOT ALTER OR REMOVE ANY TRADEMARK, COPYRIGHT OR
        OTHER NOTICE FROM COPIES OF CONTENT. WE RESERVE ALL RIGHTS IN AND TITLE
        TO ALL MATERIAL. ALL TRADEMARKS, SERVICE MARKS, TRADE NAMES, TRADE DRESS
        AND LOGOS APPEARING ON THE SITE ARE THE PROPERTY OF THEIR RESPECTIVE
        OWNER AYMPER MARKETS.
      </>
    ),
  },
  {
    title: "PAID COURSE CONTENT",
    description: (
      <>
        1). PREMIUM PACKAGE: PREMIUM PACKAGE COURSE IS COMPLETELY BASED ON
        ONLINE. ONCE USER IS PAID FOR THE PACKAGE HE HAS FULL LIFETIME ACCESS TO
        THE WEBSITE PORTAL WHERE HE CAN COMPLETE THE COURSE ANYTIME AND AS MANY
        TIMES HE WANTS. THERE WILL BE NUMEROUS UPDATES AND MODIFICATION TO THE
        COURSE CONTENT AND IT’S STRATEGY AND METHODOLOGY AND USER WILL NOTIFY
        FOR THE SAME.
        <br />
        <br />
        2). SUPER PREMIUM PACKAGE: SUPER PREMIUM PACKAGE HAS ALL FEATURES OF
        PREMIUM PACKAGE, BUT SUPER PREMIUM PACKAGE IS MORE DEDICATED. SUPER
        PREMIUM COURSE IS A SEMINAR COURSE WHERE USER NEED TO BE PRESENT AT
        CLASSES PHYSICALLY. ONCE BOUGHT THE SUPER PREMIUM PACKAGE COURSE, USER
        NEED TO WAIT FOR THE SEAT AVAILABILITY. SUPER PREMIUM COURSE DATE AND
        PLACE WILL BE DECIDED BY AYMPER MARKETS ONLY, ONCE USER PAID, AYMPER
        MARKETS ADMIN WILL PERSONALLY CALL THE USER TO BOOK THE DATE OF COURSE.
        IF USER CANNOT COME TO THE COURSE DESTINATION OR WANT TO COMPLETE THE
        COURSE ONLINE, HE CAN ASK AYMPER MARKETS ADMIN FOR ONLINE WEBINAR
        INSTEAD OF SEMINAR AT ASK@AYMPER.COM
      </>
    ),
  },
  {
    title: "LIFETIME ACCESS TERMS",
    description: (
      <>
        LIFETIME MEANS COMPLETELY LIFETIME, BUT THERE SHOULD BE SOME USER
        ACTIVITY FROM THE DATE OF STARTING SUBSCRIPTION. VALIDITY OF PREMIUM AND
        SUPER PREMIUM COURSE WILL BE FOR 3 YEARS. USER CAN EXTEND THEIR VALIDITY
        BY BEING ACTIVE ONLINE IN THE PORTAL, EVEN IF IT’S FOR ONCE TO KEEP HIS
        ACCOUNT RUNNING. IF THERE IS NO USER ACTIVITY FOR 3 YEARS STRAIGHT,
        ACCOUNT WILL BE TEMPORARILY DISABLED. FOR RE-ENABLING THE ACCOUNT AGAIN,
        USER NEED TO SEND EMAIL TO ASK@AYMPER.COM AND IT WILL BE ACTIVATED AS
        SOON AS POSSIBLE FOR FREE, THERE WILL BE NO CHARGES AS WE BELIEVE IN ONE
        TIME PAY AND GET THE SERVICE FOR LIFETIME. THERE WILL BE NO MONTHLY
        SUBSCRIPTION. ONCE USER IS PAID FOR PREMIUM OR SUPER PREMIUM PACKAGE
        THEY WILL ENJOY THE SERVICE FOR LIFETIME.
        <br />
        <br />
        LIFETIME ACCESS TERM IS USED FOR THE WEBSITE’S LIFE NOT OF USERS. USERS
        CAN ENJOY THE SERVICE TILL THERE ARE AYMPER MARKETS. THERE WILL BE
        MINIMUM 3 YEARS OF SERVICE GUARANTEED FOR EACH USER. IF THERE IS ANY
        SUDDEN CLOSURE OF THE AYMPER MARKETS SERVICES DUE TO ANY ISSUES IN
        FUTURE, IN THAT CASE, USER’S MONEY WILL BE REFUNDED. REFUND WILL BE MADE
        ONLY FOR NEW USER WHOSE ACCOUNT IS 1 MONTH OLD, AS THE COURSE CAN BE
        COMPLETE IN 10 DAYS, SO USER HAVE A GOOD TIME TO COMPLETE.
      </>
    ),
  },
  {
    title: "CERTIFICATION POLICY",
    description: `WE AYMPER MARKETS ARE 9001 2015 ISO CERTIFIED COMPANY. CERTIFICATE OF COMPLETION IS PROVIDED TO THE USER ONCE THEY COMPLETE THE PREMIUM OR SUPER PREMIUM COURSE. THE CERTIFICATE CAN BE ISSUED IN PHYSICAL OR DIGITAL FORM.`,
  },
  {
    title: "COURSE CONTENT COPYRIGHT",
    description: (
      <>
        ALTHOUGH WE RESERVE THE RIGHT TO EDIT OR MODIFY COURSE CONTENT PRIOR TO
        THEIR INCLUSION ON THE SERVICES. YOU ALSO AGREE THAT YOU WILL NOT:
        <br />
        <br />
        REPRODUCE, DISTRIBUTE, REPUBLISH OR RETRANSMIT COURSE CONTENT POSTED BY
        AYMPER MARKETS. USERS WITHOUT THE PERMISSION OF “AYMPER MARKETS”; TAKE
        ANY ACTION THAT IMPOSES AN UNREASONABLE OR DISPROPORTIONATELY LARGE LOAD
        ON OUR INFRASTRUCTURE; OR:
        <br />
        <br />
        INTERFERE OR ATTEMPT TO INTERFERE WITH THE PROPER WORKING OF THE
        SERVICES, ANY ACTIVITIES CONDUCTED ON OR THROUGH THE SERVICES, OR ANY
        NETWORKS THROUGH WHICH YOU ACCESS THE SERVICES.
      </>
    ),
  },
  {
    title: "AYMPER MARKETS PROPRIETARY RIGHTS",
    description: (
      <>
        ALL SERVICES SOFTWARE, DESIGN, TEXT, IMAGES, PHOTOGRAPHS, ILLUSTRATIONS,
        AUDIO AND VIDEO MATERIAL, ARTWORK, GRAPHIC MATERIAL, DATABASE,
        PROPRIETARY INFORMATION AND ALL COPYRIGHTABLE OR OTHERWISE LEGALLY
        PROTECTABLE ELEMENTS OF THE SERVICES, INCLUDING, BUT NOT LIMITED TO, THE
        SELECTION, SEQUENCE AND ‘LOOK AND FEEL’ AND ARRANGEMENT OF ITEMS, AND
        ALL TRADEMARKS, SERVICE MARKS AND TRADE NAMES, ARE THE PROPERTY OF
        “AYMPER MARKETS”, ITS SUBSIDIARIES, AFFILIATES, LICENSORS OR SUPPLIERS
        AND ARE LEGALLY PROTECTED, WITHOUT LIMITATION, UNDER INDIAN, AS WELL AS
        APPLICABLE FOREIGN, LAWS, REGULATIONS AND TREATIES. THE COMPILATION OF
        ALL CONTENT ON WWW.AYMPER.COM IS THE EXCLUSIVE PROPERTY OF “AYMPER
        MARKETS”. YOU MAY NOT REPRODUCE, MODIFY, CREATE DERIVATIVE WORKS FROM,
        DISPLAY, PERFORM, PUBLISH, DISTRIBUTE, DISSEMINATE, BROADCAST OR
        CIRCULATE TO ANY THIRD PARTY (INCLUDING, WITHOUT LIMITATION, ON OR VIA A
        THIRD-PARTY WEB SITE), OR OTHERWISE USE, ANY MATERIALS CONTAINED ON THE
        SERVICES WITHOUT THE EXPRESS PRIOR WRITTEN CONSENT OF “AYMPER MARKETS”
        OR ITS OWNER. IN PARTICULAR, YOU MAY NOT FRAME ANY MATERIAL WITHOUT THE
        EXPRESS PRIOR WRITTEN CONSENT OF “AYMPER MARKETS” OR THE MATERIAL OWNER.
        YOU MUST NOT ALTER, DELETE OR CONCEAL ANY COPYRIGHT OR OTHER NOTICES
        CONTAINED ON THE SERVICES, INCLUDING NOTICES ON ANY MATERIAL YOU
        TRANSMIT, PRINT OR REPRODUCE FROM THE SERVICES. ANY UNAUTHORIZED OR
        PROHIBITED USE OF ANY MATERIAL, MAY SUBJECT YOU TO CIVIL LIABILITY OR
        CRIMINAL PROSECUTION, OR BOTH, UNDER APPLICABLE FEDERAL AND STATE LAWS.
        YOU FURTHER AGREE NOT TO ACCESS THE SERVICE BY ANY MEANS OTHER THAN
        PERSONAL OR NON-COMMERCIAL PURPOSE THROUGH THE INTERFACE THAT IS
        PROVIDED BY “AYMPER MARKETS” FOR USE IN ACCESSING THE SERVICE.`,
      </>
    ),
  },
  {
    title: "PROMOTIONS TERMS",
    description: `SOME OF OUR SERVICES MAY FROM TIME TO TIME CONDUCT PROMOTIONS, INCLUDING, BUT NOT LIMITED TO, EDUCATIONAL SEMINAR, SOCIAL MEDIA SITE POSTING, PHYSICAL APPEARANCE FOR EDUCATIONAL TRAINING CAMPAIGNS AND MEETINGS. EACH PROMOTION WILL HAVE ADDITIONAL TERMS, CONDITIONS AND RULES WHICH WILL BE POSTED OR OTHERWISE MADE AVAILABLE TO YOU AND, FOR PURPOSES OF EACH PROMOTION IN WHICH YOU PARTICIPATE, WILL BE DEEMED INCORPORATED BY REFERENCE INTO THESE TOS (AND THEREFORE A PART OF YOUR AGREEMENT WITH “AYMPER MARKETS”).`,
  },
  {
    title: "PAID AND NON-PAID BASED SERVICES",
    description: `ALL OF OUR SERVICES NOT REQUIRE PAYING A FEE TO ACCESS OR USING SUCH SERVICE, THERE IS FREE SERVICE TOO. AS DESCRIBED IN THE SPECIFIC CONDITIONS INCLUDED WHERE THOSE OF SOME SERVICES ARE OFFERED ARE CHARGED AND PAID ONCE. YOU AGREE TO PAY FEES AND CHARGES THAT YOU INCUR. UNLESS OTHERWISE NOTED, ALL CURRENCY REFERENCES ARE IN INDIAN RUPEES. WE MAY, UPON NOTICE IF REQUIRED BY APPLICABLE LAWS, AT ANY TIME CHANGE THE AMOUNT OF, OR BASIS FOR DETERMINING, ANY FEE OR CHARGE, OR INSTITUTE NEW FEES OR CHARGES. ALL FEES AND CHARGES ARE PAYABLE IN ACCORDANCE WITH PAYMENT TERMS IN EFFECT AT THE TIME THE FEE OR CHARGE BECOMES PAYABLE. THE PREMIUM PACKAGE AND SUPER PREMIUM PACKAGE IS PAID COURSE AND ONCE PAID, THE SERVICE IS FOR LIFETIME, UNLESS SOME USER VIOLATE OUR TERMS AND CONDITION AND END UP WITH SERVICE CANCELLATION.`,
  },
  {
    title: "NO REFUND POLICY",
    description: (
      <>
        THERE IS 2 PAID SERVICE (PREMIUM AND SUPER PREMIUM) IN AYMPER MARKETS
        ALONG WITH 1 FREE SERVICE. ONCE USER PAID FOR ANY PREMIUM PAID SERVICE,
        THERE WILL BE NO REFUND POSSIBLE. PLEASE GO THROUGH AYMPER MARKETS
        WEBSITE (WWW.AYMPER.COM) TO GET THE INFORMATION WHAT YOU ARE PAYING FOR
        BEFORE SUBSCRIBING TO ANY PAID PACKAGE. USER ALSO MUST READ OUR TERMS
        AND CONDITION BEFORE SUBSCRIBING TO ANY PAID PACKAGE.
        <br />
        <br />
        NO REFUND IF USER DOES NOT LIKE THE CONTENT COURSE OR USER WANTS TO
        EXCHANGE THE PREMIUM PACKAGE FOR SUPER PREMIUM, VICE-VERSA OR USER IS
        NOT SATISFIED OR HE DOESN’T UNDERSTAND THE CONTENT COURSE. REFUND WILL
        BE NOT POSSIBLE IN ANY CASE AS BOTH PREMIUM AND SUPER PREMIUM COURSE
        PACKAGE SUBSCRIPTION IS FOR LIFETIME ACCESS.
      </>
    ),
  },
  {
    title: "REGISTRATIONS OBLIGATIONS AND SERVICE TERMINATION",
    description: (
      <>
        OUR SERVICES REQUIRE THAT YOU REGISTER WITH THAT SERVICE IN ORDER TO
        ACCESS OUR MAIN CONTENT PORTAL TO USE IT. IF SUCH REGISTRATION IS
        REQUIRED, YOU AGREE THAT YOU WILL PROVIDE ACCURATE INFORMATION (SUCH AS
        YOUR REAL NAME AND A VALID EMAIL ADDRESS) AND WILL UPDATE YOUR RELEVANT
        INFORMATION IF IT BECOMES OUTDATED. IF YOU PROVIDE ANY INFORMATION THAT
        IS, OR THAT “AYMPER MARKETS” IN ITS REASONABLE DISCRETION DETERMINES MAY
        BE, UNTRUE, INACCURATE, NOT CURRENT OR INCOMPLETE, “AYMPER MARKETS” HAS
        THE RIGHT, WITHOUT PRIOR NOTICE, TO SUSPEND OR TERMINATE YOUR ACCOUNT
        AND REFUSE ANY AND ALL CURRENT OR FUTURE USE OF THE SERVICES (OR ANY
        PORTION THEREOF). FOR MORE DETAILED INFORMATION ABOUT HOW WE TREAT THE
        REGISTRATION INFORMATION YOU PROVIDE TO US, PLEASE SEE OUR PRIVACY
        NOTICE, WHICH IS INCORPORATED BY REFERENCE INTO THESE TOS (AND THEREFORE
        A PART OF YOUR AGREEMENT WITH US).
        <br />
        <br />
        WE HAVE THE RIGHT, BUT NOT THE OBLIGATION, TO TAKE ANY OF THE FOLLOWING
        ACTIONS IN OUR SOLE DISCRETION AT ANY TIME AND FOR ANY REASON WITHOUT
        GIVING YOU ANY PRIOR NOTICE:
        <br />
        <br />
        RESTRICT, SUSPEND OR TERMINATE YOUR ACCESS TO ALL OR ANY PART OF OUR
        SERVICES;
        <br />
        <br />
        DEACTIVATE OR DELETE YOUR ACCOUNTS AND ALL RELATED INFORMATION IN YOUR
        DASHBOARD.
        <br />
        <br />
        ESTABLISH GENERAL PRACTICES AND LIMITS CONCERNING USE OF THE SERVICES WE
        MAY TAKE ANY OF THE ABOVE ACTIONS FOR ANY LEGITIMATE BUSINESS REASON, AS
        DETERMINED BY “AYMPER MARKETS” IN ITS SOLE DISCRETION, INCLUDING, BUT
        NOT BE LIMITED TO, (A) BREACHES OR VIOLATIONS OF THE TOS OR OTHER
        INCORPORATED AGREEMENTS OR GUIDELINES, (B) REQUESTS BY LAW ENFORCEMENT
        OR OTHER GOVERNMENT AGENCIES, (C) A REQUEST BY YOU, (D) DISCONTINUANCE
        OR MATERIAL MODIFICATION TO THE SERVICES (OR ANY PART THEREOF), AND (E)
        UNEXPECTED TECHNICAL OR SECURITY ISSUES OR PROBLEMS. YOU AGREE THAT WE
        WILL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR TAKING ANY OF THESE
        ACTIONS.
      </>
    ),
  },
];
